load("//build/bazelutil/unused_checker:unused.bzl", "get_x_data")
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "demo",
    srcs = ["demo.go"],
    importpath = "github.com/cockroachdb/cockroach/pkg/ccl/cliccl/demo",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ccl",
        "//pkg/cli/democluster",
    ],
)

get_x_data(name = "get_x_data")
